packages:
  - "packages/*"
  - "examples/*/*"
catalog:
  effect: 4.0.0-rc.112
  "@effect/platform-node": 4.0.0-rc.112
  "@effect/platform-browser": 4.0.0-rc.112
allowBuilds:
  esbuild: true
  msgpackr-extract: true
