// Generated by @effect-opcua/codegen. Do not edit manually.

import { Opcua } from "@effect-opcua/client";
import { Schema } from "effect";

import * as NodeIds from "./nodeIds.js";

export const Commands = {
  Request: Opcua.variable({
    nodeId: NodeIds.Commands.Request,
    codec: Opcua.schema(Schema.String),
    access: "write",
  }),
} as const;
