import type {
  CodegenModel,
  DataTypeNodeIdDefinition,
  EnumDefinition,
  GeneratedFile,
  NodeIdDefinition,
  SchemaExpression,
  StructureDefinition,
  VariableCodecExpression,
  VariableDefinition,
} from "./types.js";

export const generatedHeader =
  "// Generated by @effect-opcua/codegen. Do not edit manually.";

export const emit = (model: CodegenModel): readonly GeneratedFile[] => [
  {
    path: "nodeIds.ts",
    contents: emitNodeIds(model.nodeIds, model.dataTypeNodeIds),
  },
  { path: "enums.ts", contents: emitEnums(model.enums) },
  { path: "structures.ts", contents: emitStructures(model.structures) },
  { path: "variables.ts", contents: emitVariables(model.variables) },
  { path: "index.ts", contents: emitIndex() },
];

export const emitTypescript = emit;

type TreeNode = {
  value?: string;
  variable?: VariableDefinition;
  children: Map<string, TreeNode>;
};

const emitNodeIds = (
  nodeIds: readonly NodeIdDefinition[],
  dataTypeNodeIds: readonly DataTypeNodeIdDefinition[],
) => {
  const root: TreeNode = { children: new Map() };
  for (const nodeId of [...nodeIds].sort(pathSort)) {
    let current = root;
    for (const segment of nodeId.generatedPath) {
      const child = current.children.get(segment) ?? { children: new Map() };
      current.children.set(segment, child);
      current = child;
    }
    current.value = nodeId.nodeId;
  }
  if (dataTypeNodeIds.length > 0) {
    const dataTypes: TreeNode = { children: new Map() };
    for (const dataType of [...dataTypeNodeIds].sort((left, right) =>
      left.name.localeCompare(right.name),
    )) {
      dataTypes.children.set(dataType.name, {
        value: dataType.nodeId,
        children: new Map(),
      });
    }
    root.children.set("DataTypes", dataTypes);
  }
  const topLevel = [...root.children.entries()].sort(keySort);
  if (topLevel.length === 0) return emitEmptyModule();
  return [
    generatedHeader,
    "",
    ...topLevel.map(
      ([key, value]) => `export const ${key} = ${emitTree(value, 0)} as const;`,
    ),
    "",
  ].join("\n");
};

const emitTree = (node: TreeNode, depth: number): string => {
  if (node.value !== undefined && node.children.size === 0) {
    return JSON.stringify(node.value);
  }
  const lines = ["{"];
  for (const [key, child] of [...node.children.entries()].sort(keySort)) {
    lines.push(`${indent(depth + 1)}${key}: ${emitTree(child, depth + 1)},`);
  }
  lines.push(`${indent(depth)}}`);
  return lines.join("\n");
};

const emitEnums = (enums: readonly EnumDefinition[]) => {
  if (enums.length === 0) return emitEmptyModule();
  const lines = [
    generatedHeader,
    "",
    'import { Schema } from "effect";',
    "",
  ];
  for (const item of [...enums].sort((left, right) =>
    left.name.localeCompare(right.name),
  )) {
    lines.push(`export const ${item.name} = {`);
    for (const member of item.members) {
      lines.push(`${indent(1)}${member.name}: ${member.value},`);
    }
    lines.push("} as const;");
    lines.push("");
    lines.push(
      `export type ${item.name} = (typeof ${item.name})[keyof typeof ${item.name}];`,
    );
    lines.push("");
    lines.push(`export const ${item.name}Schema = Schema.Literals([`);
    for (const member of item.members) {
      lines.push(`${indent(1)}${item.name}.${member.name},`);
    }
    lines.push("]);");
    lines.push("");
  }
  return lines.join("\n");
};

const emitStructures = (structures: readonly StructureDefinition[]) => {
  if (structures.length === 0) return emitEmptyModule();
  const lines = [
    generatedHeader,
    "",
    'import { Opcua } from "@effect-opcua/client";',
    'import { Schema } from "effect";',
    "",
    'import * as Enums from "./enums.js";',
    'import * as NodeIds from "./nodeIds.js";',
    "",
  ];
  for (const item of structures) {
    lines.push(`export const ${item.name}Schema = Schema.Struct({`);
    for (const field of item.fields) {
      const schema = emitFieldSchema(field.schema);
      lines.push(
        `${indent(1)}${field.name}: ${
          field.optional ? `Schema.optional(${schema})` : schema
        },`,
      );
    }
    lines.push("});");
    lines.push("");
    lines.push(`export type ${item.name} = typeof ${item.name}Schema.Type;`);
    lines.push("");
    lines.push(`export const ${item.name} = Opcua.structure({`);
    lines.push(`${indent(1)}name: ${JSON.stringify(item.browseName)},`);
    lines.push(`${indent(1)}dataTypeId: NodeIds.DataTypes.${item.name},`);
    lines.push(`${indent(1)}schema: ${item.name}Schema,`);
    lines.push("});");
    lines.push("");
  }
  return lines.join("\n");
};

const emitVariables = (variables: readonly VariableDefinition[]) => {
  const lines = [
    generatedHeader,
    "",
    'import { Opcua } from "@effect-opcua/client";',
    'import { Schema } from "effect";',
    "",
    'import * as Enums from "./enums.js";',
    'import * as NodeIds from "./nodeIds.js";',
    'import * as Structures from "./structures.js";',
    "",
  ];
  if (variables.length === 0) {
    lines.push("export {};", "");
    return lines.join("\n");
  }
  const root = variableTree(variables);
  for (const [key, child] of [...root.children.entries()].sort(keySort)) {
    lines.push(`export const ${key} = ${emitVariableTree(child, 0)} as const;`);
    lines.push("");
  }
  return lines.join("\n");
};

const variableTree = (variables: readonly VariableDefinition[]) => {
  const root: TreeNode = { children: new Map() };
  for (const variable of [...variables].sort(pathSort)) {
    let current = root;
    for (const segment of variable.generatedPath) {
      const child = current.children.get(segment) ?? { children: new Map() };
      current.children.set(segment, child);
      current = child;
    }
    current.variable = variable;
  }
  return root;
};

const emitVariableTree = (node: TreeNode, depth: number): string => {
  if (node.variable && node.children.size === 0) {
    return emitVariable(node.variable, depth);
  }
  const lines = ["{"];
  for (const [key, child] of [...node.children.entries()].sort(keySort)) {
    lines.push(
      `${indent(depth + 1)}${key}: ${emitVariableTree(child, depth + 1)},`,
    );
  }
  lines.push(`${indent(depth)}}`);
  return lines.join("\n");
};

const emitVariable = (variable: VariableDefinition, depth: number) => {
  const lines = ["Opcua.variable({"];
  lines.push(
    `${indent(depth + 1)}nodeId: NodeIds.${variable.generatedPath.join(".")},`,
  );
  lines.push(`${indent(depth + 1)}codec: ${emitCodec(variable.codec)},`);
  if (variable.access === "readWrite") {
    lines.push(`${indent(depth + 1)}access: "readWrite",`);
  }
  lines.push(`${indent(depth)}})`);
  return lines.join("\n");
};

const emitCodec = (codec: VariableCodecExpression) => {
  switch (codec._tag) {
    case "Schema":
      return `Opcua.schema(Schema.${codec.schema})`;
    case "SchemaArray":
      return `Opcua.schema(Schema.Array(Schema.${codec.element}))`;
    case "Enum":
      return `Opcua.schema(Enums.${codec.name}Schema)`;
    case "EnumArray":
      return `Opcua.schema(Schema.Array(Enums.${codec.name}Schema))`;
    case "Structure":
      return `Structures.${codec.name}`;
    case "StructureArray":
      return `Opcua.structureArray(Structures.${codec.name})`;
    case "Dynamic":
      return "Opcua.dynamic()";
  }
};

const emitFieldSchema = (schema: SchemaExpression): string => {
  switch (schema._tag) {
    case "Scalar":
      return `Schema.${schema.schema}`;
    case "Array":
      return `Schema.Array(${emitFieldSchema(schema.item)})`;
    case "Enum":
      return `Enums.${schema.name}Schema`;
    case "Structure":
      return `${schema.name}Schema`;
    case "Unknown":
      return "Schema.Unknown";
  }
};

const emitEmptyModule = () =>
  [generatedHeader, "", "export {};", ""].join("\n");

const emitIndex = () =>
  [
    generatedHeader,
    "",
    'export * as NodeIds from "./nodeIds.js";',
    'export * as Enums from "./enums.js";',
    'export * as Structures from "./structures.js";',
    'export * as Variables from "./variables.js";',
    "",
  ].join("\n");

const pathSort = <
  T extends { readonly generatedPath: readonly string[]; readonly path?: readonly string[] },
>(
  left: T,
  right: T,
) =>
  left.generatedPath.join(".").localeCompare(right.generatedPath.join(".")) ||
  (left.path ?? []).join(".").localeCompare((right.path ?? []).join("."));

const keySort = (
  left: readonly [string, TreeNode],
  right: readonly [string, TreeNode],
) => left[0].localeCompare(right[0]);

const indent = (depth: number) => "  ".repeat(depth);
