import type {
  CodecExpression,
  CodegenIr,
  GeneratedFile,
  NodeIdDefinition,
} from "./types.js";

export const generatedHeader =
  "// Generated by @effect-opcua/codegen. Do not edit manually.";

export const emitTypescript = (ir: CodegenIr): readonly GeneratedFile[] => [
  { path: "nodeIds.ts", contents: emitNodeIds(ir.nodeIds) },
  { path: "enums.ts", contents: emitEmptyModule() },
  { path: "structures.ts", contents: emitEmptyModule() },
  { path: "variables.ts", contents: emitVariables(ir) },
  { path: "methods.ts", contents: emitEmptyModule() },
  { path: "index.ts", contents: emitIndex() },
];

type TreeNode = {
  value?: string;
  children: Map<string, TreeNode>;
};

const emitNodeIds = (nodeIds: readonly NodeIdDefinition[]) => {
  if (nodeIds.length === 0) return emitEmptyModule();
  const root: TreeNode = { children: new Map() };
  for (const nodeId of [...nodeIds].sort((left, right) =>
    left.browsePath.localeCompare(right.browsePath),
  )) {
    let current = root;
    for (const segment of nodeId.browsePathSegments) {
      const child = current.children.get(segment) ?? { children: new Map() };
      current.children.set(segment, child);
      current = child;
    }
    current.value = nodeId.nodeId;
  }
  const topLevel = [...root.children.entries()].sort(keySort);
  return [
    generatedHeader,
    "",
    ...topLevel.map(
      ([key, value]) => `export const ${key} = ${emitTree(value, 0)} as const;`,
    ),
    "",
  ].join("\n");
};

const emitTree = (node: TreeNode, depth: number): string => {
  if (node.value !== undefined && node.children.size === 0) {
    return JSON.stringify(node.value);
  }
  const lines = ["{"];
  for (const [key, child] of [...node.children.entries()].sort(keySort)) {
    lines.push(`${indent(depth + 1)}${key}: ${emitTree(child, depth + 1)},`);
  }
  lines.push(`${indent(depth)}}`);
  return lines.join("\n");
};

const emitVariables = (ir: CodegenIr) => {
  const lines = [
    generatedHeader,
    "",
    'import { Opcua } from "@effect-opcua/client";',
    'import { Schema } from "effect";',
    "",
    'import * as NodeIds from "./nodeIds.js";',
    "",
  ];
  if (ir.variables.length === 0) {
    lines.push("export {};", "");
    return lines.join("\n");
  }
  for (const variable of ir.variables) {
    lines.push(`export const ${variable.exportName} = Opcua.variable({`);
    lines.push(`  nodeId: NodeIds.${variable.nodeIdPath.join(".")},`);
    lines.push(`  codec: ${emitCodec(variable.codec)},`);
    if (variable.access === "readWrite") {
      lines.push('  access: "readWrite",');
    }
    lines.push("});");
    lines.push("");
  }
  return lines.join("\n");
};

const emitCodec = (codec: CodecExpression) => {
  switch (codec._tag) {
    case "Schema":
      return `Opcua.schema(Schema.${codec.schema})`;
    case "SchemaArray":
      return `Opcua.schema(Schema.Array(Schema.${codec.element}))`;
    case "Dynamic":
      return "Opcua.dynamic()";
  }
};

const emitEmptyModule = () =>
  [generatedHeader, "", "export {};", ""].join("\n");

const emitIndex = () =>
  [
    generatedHeader,
    "",
    'export * as NodeIds from "./nodeIds.js";',
    'export * as Enums from "./enums.js";',
    'export * as Structures from "./structures.js";',
    'export * as Variables from "./variables.js";',
    'export * as Methods from "./methods.js";',
    "",
  ].join("\n");

const keySort = (
  left: readonly [string, TreeNode],
  right: readonly [string, TreeNode],
) => left[0].localeCompare(right[0]);

const indent = (depth: number) => "  ".repeat(depth);
